// WORKSPACE-PATH:allow-fixture - this file is a test fixture that simulates a foreign
// checkout root, so the sdkwork-<name> segment below is the value under assertion rather
// than a binding to a real sibling checkout. PORTABILITY_SPEC.md section 5.2 governs it.
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { readFileSync } from 'node:fs';

import {
  ensureTauriTargetClean,
  removeDirectoryWithRetriesSync,
} from './ensure-tauri-target-clean.mjs';
import {
  DEFAULT_NODE_VERSION,
  DEFAULT_OPENCLAW_VERSION,
} from './openclaw-release.mjs';
import { derivePreviousNumericVersion } from './test-support/version-fixtures.mjs';

const modulePath = path.resolve(import.meta.dirname, 'ensure-tauri-target-clean.mjs');

assert.match(
  readFileSync(modulePath, 'utf8'),
  /if \(invokedScriptPath && invokedScriptPath === currentModulePath\) \{\s*try \{\s*runCli\(\);\s*\} catch \(error\) \{\s*console\.error\(error instanceof Error \? error\.message : String\(error\)\);\s*process\.exit\(1\);\s*\}\s*\}/s,
  'ensure-tauri-target-clean must wrap the CLI entrypoint with a top-level error handler',
);
assert.equal(
  typeof removeDirectoryWithRetriesSync,
  'function',
  'ensure-tauri-target-clean must export removeDirectoryWithRetriesSync',
);
assert.match(
  readFileSync(modulePath, 'utf8'),
  /if \(targetInspection\.staleEntries\.length > 0\) \{\s*removeDirectoryWithRetriesSync\(targetInspection\.targetDir\);/,
  'ensure-tauri-target-clean must remove the full target directory only when stale permission manifests require it',
);
assert.match(
  readFileSync(modulePath, 'utf8'),
  /cleanupBundledOpenClawTargetResources\(targetInspection\)/,
  'ensure-tauri-target-clean must remove stale packaged OpenClaw target resources without deleting the full Cargo target directory',
);

function withTempDir(callback) {
  const tempDir = mkdtempSync(path.join(os.tmpdir(), 'tauri-target-clean-'));

  try {
    callback(tempDir);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function writePermissionManifest(srcTauriDir, manifestName, permissionEntries) {
  const manifestDir = path.join(srcTauriDir, 'target', 'debug', 'build', 'tauri-test', 'out');
  mkdirSync(manifestDir, { recursive: true });
  writeFileSync(path.join(manifestDir, manifestName), JSON.stringify(permissionEntries), 'utf8');
}

function writeJson(filePath, value) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

const staleOpenClawVersion = derivePreviousNumericVersion(DEFAULT_OPENCLAW_VERSION);
const staleNodeVersion = derivePreviousNumericVersion(DEFAULT_NODE_VERSION);

{
  const removedPaths = [];
  const logLines = [];
  let attempts = 0;
  removeDirectoryWithRetriesSync('D:\\workspace\\sdkwork-agentstudio-pc-desktop\\src-tauri\\target', {
    removeImpl: (targetPath, options) => {
      removedPaths.push({ targetPath, options });
      attempts += 1;
      if (attempts === 1) {
        const error = new Error('resource busy or locked');
        error.code = 'EBUSY';
        throw error;
      }
    },
    retryCount: 2,
    retryDelayMs: 1,
    sleepImpl: () => {},
    logger: (message) => {
      logLines.push(message);
    },
  });

  assert.equal(
    attempts,
    2,
    'ensure-tauri-target-clean must retry target cleanup after transient Windows file locks',
  );
  assert.ok(
    logLines.some((line) => line.includes('Retrying cleanup')),
    'ensure-tauri-target-clean must log retried stale target cleanup attempts after transient Windows file locks',
  );
  assert.deepEqual(
    removedPaths.map((entry) => entry.targetPath),
    [
      'D:\\workspace\\sdkwork-agentstudio-pc-desktop\\src-tauri\\target',
      'D:\\workspace\\sdkwork-agentstudio-pc-desktop\\src-tauri\\target',
    ],
    'ensure-tauri-target-clean must retry the same target directory path until cleanup succeeds',
  );
}

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const permissionFile = path.join(
    targetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  mkdirSync(path.dirname(permissionFile), { recursive: true });
  writeFileSync(permissionFile, 'identifier = "app:hide"', 'utf8');
  writePermissionManifest(srcTauriDir, 'tauri-core-app-permission-files', [
    process.platform === 'win32' ? `\\\\?\\${permissionFile}` : permissionFile,
  ]);

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(result.removedTarget, false, 'healthy permission manifests should not trigger cleanup');
  assert.equal(existsSync(targetDir), true, 'healthy target directory must stay intact');
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const missingPermissionFile = path.join(
    targetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  writePermissionManifest(srcTauriDir, 'tauri-core-app-permission-files', [missingPermissionFile]);

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(result.removedTarget, true, 'stale permission manifests must trigger cleanup');
  assert.equal(existsSync(targetDir), false, 'stale target directory must be removed');
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  writeJson(path.join(srcTauriDir, 'resources', 'openclaw', 'manifest.json'), {
    schemaVersion: 2,
    runtimeId: 'openclaw',
    openclawVersion: DEFAULT_OPENCLAW_VERSION,
    requiredExternalRuntimes: ['nodejs'],
    requiredExternalRuntimeVersions: {
      nodejs: DEFAULT_NODE_VERSION,
    },
    platform: 'windows',
    arch: 'x64',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  });
  writeJson(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw-runtime', 'manifest.json'), {
    schemaVersion: 1,
    runtimeId: 'openclaw',
    openclawVersion: staleOpenClawVersion,
    nodeVersion: staleNodeVersion,
    platform: 'windows',
    arch: 'x64',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  });

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(
    result.removedTarget,
    false,
    'legacy openclaw-runtime resource directories must not delete the full target cache',
  );
  assert.deepEqual(
    result.removedResourceDirs,
    [path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw-runtime')],
    'legacy packaged OpenClaw target resources must be removed directly',
  );
  assert.equal(existsSync(targetDir), true, 'Cargo target cache must stay intact after resource cleanup');
  assert.equal(
    existsSync(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw-runtime')),
    false,
    'legacy packaged OpenClaw target resources must be removed',
  );
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const sourceManifest = {
    schemaVersion: 2,
    runtimeId: 'openclaw',
    openclawVersion: DEFAULT_OPENCLAW_VERSION,
    requiredExternalRuntimes: ['nodejs'],
    requiredExternalRuntimeVersions: {
      nodejs: DEFAULT_NODE_VERSION,
    },
    platform: 'windows',
    arch: 'x64',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  };
  writeJson(path.join(srcTauriDir, 'resources', 'openclaw', 'manifest.json'), sourceManifest);
  writeJson(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw', 'manifest.json'), {
    ...sourceManifest,
    openclawVersion: staleOpenClawVersion,
  });

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(
    result.removedTarget,
    false,
    'mismatched packaged OpenClaw manifests must not delete the full target cache',
  );
  assert.deepEqual(
    result.removedResourceDirs,
    [path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw')],
    'mismatched packaged OpenClaw target resource directories must be removed directly',
  );
  assert.equal(existsSync(targetDir), true, 'Cargo target cache must stay intact after resource cleanup');
  assert.equal(
    existsSync(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw')),
    false,
    'mismatched packaged OpenClaw target resources must be removed',
  );
});

withTempDir((tempDir) => {
  const desktopPackageDir = path.join(tempDir, 'sdkwork-agentstudio-pc-desktop');
  const srcTauriDir = path.join(desktopPackageDir, 'src-tauri');
  const packageTargetDir = path.join(desktopPackageDir, '.tauri-target');
  writeJson(path.join(srcTauriDir, 'resources', 'openclaw', 'manifest.json'), {
    schemaVersion: 2,
    runtimeId: 'openclaw',
    openclawVersion: DEFAULT_OPENCLAW_VERSION,
    requiredExternalRuntimes: ['nodejs'],
    requiredExternalRuntimeVersions: {
      nodejs: DEFAULT_NODE_VERSION,
    },
    platform: 'windows',
    arch: 'x64',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  });
  writeJson(
    path.join(packageTargetDir, 'dev', 'debug', 'resources', 'openclaw-runtime', 'manifest.json'),
    {
      schemaVersion: 1,
      runtimeId: 'openclaw',
      openclawVersion: staleOpenClawVersion,
      nodeVersion: DEFAULT_NODE_VERSION,
      platform: 'windows',
      arch: 'x64',
      cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
    },
  );

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(
    result.removedTarget,
    false,
    'legacy desktop .tauri-target OpenClaw resources must not delete the full target cache',
  );
  assert.deepEqual(result.removedResourceDirs, [
    path.join(packageTargetDir, 'dev', 'debug', 'resources', 'openclaw-runtime'),
  ]);
  assert.equal(existsSync(packageTargetDir), true, 'desktop .tauri-target cache root must stay intact');
  assert.equal(
    existsSync(path.join(packageTargetDir, 'dev', 'debug', 'resources', 'openclaw-runtime')),
    false,
    'legacy desktop .tauri-target OpenClaw resources must be removed directly',
  );
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');

  mkdirSync(path.join(srcTauriDir, 'resources', 'openclaw'), { recursive: true });
  writeFileSync(path.join(srcTauriDir, 'resources', 'openclaw', '.gitkeep'), '', 'utf8');
  writeJson(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw', 'manifest.json'), {
    schemaVersion: 1,
    runtimeId: 'openclaw',
    openclawVersion: staleOpenClawVersion,
    nodeVersion: DEFAULT_NODE_VERSION,
    platform: 'windows',
    arch: 'x64',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  });

  const result = ensureTauriTargetClean(srcTauriDir, {
    env: {
      SDKWORK_DESKTOP_TARGET_PLATFORM: 'windows',
      SDKWORK_DESKTOP_TARGET_ARCH: 'x64',
    },
  });

  assert.equal(
    result.removedTarget,
    false,
    'stale packaged target manifests must not delete the full target cache when only OpenClaw resources are stale',
  );
  assert.deepEqual(
    result.removedResourceDirs,
    [path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw')],
  );
  assert.equal(existsSync(targetDir), true, 'Cargo target cache must stay intact after resource cleanup');
  assert.equal(
    existsSync(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw')),
    false,
    'stale packaged target manifests must not survive the openclaw placeholder-only source layout',
  );
});

console.log('ok - stale Tauri target cleanup only removes invalid permission caches');
